version: '3.8'

services:
  web:
    build: ./docker/web
    container_name: web
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:80
    working_dir: /var/www/html

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: berlin
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
    - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1